name: My workflow
on: [workflow_dispatch]
jobs:
  Mario-deploy-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉"
      - uses: actions/checkout@v4
      - uses: actions/download-artifact
        with:
          name: mario_emscripten
      - run: more mario_emscripten
      # commit to repository
