name: My workflow
on: [workflow_dispatch]
jobs:
  Mario-deploy-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉"
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mario_emscripten
          github-token: ${{ secrets.PAT_mario_repo_read }}
          repository: SolegnaT/mario
      - run: more mario_emscripten
      # commit to repository
