name: My workflow
on: [workflow_dispatch]
jobs:
  Mario-deploy-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉"
      - uses: actions/checkout@v4
      # download file 
      # commit to repository
